#' Rename columns from a FormIO response dataset
#'
#' This fucntion will take a dataset object generated by FlattenSubmissions() and create an interfase to ask the user iteratively the name that they will assign to each of the columns from the object.
#' The function allows to return the new response dataset (NamesDF=T, by default), and return a dataframe with three columns: Number, OldNames and NewNames (renameDF=T)
#'
#' @param x Flattened FormIO Dataset
#'
#' @param NamesDF  TRUE by default. Will return a dataframe, called 'renamedDF', with three columns: Number, OldNames and NewNames
#' @param renameDF TRUE by default. Will return the original data frame with the new columns assigned
#'
#' @returns description list with:
#' * data frame  called 'renamedDF', with three columns: Number, OldNames and NewNames
#' * data frame with the original data frame with the new columns assigned
#'
#' @export
#'
#' @examplesIf interactive()
#' # df<-FoodTypes
#'
#' #Original Names
#' colnames(df)
#' RenameCols(df)
#'
#'
#'
#

RenameCols <- function(x, NamesDF=T, renameDF=T) {

	FlatX<-x

	renamedDF <- FlatX$ColumnNames
	colnames(renamedDF)<-c("Number", "OldNames")

	for (i in 1:nrow(renamedDF)) {
		cat("\014")
		currentcol <- renamedDF$OldNames[i]
		cat(green(paste0(i, "/", nrow(renamedDF) )))
		cat("\n")
		cat("Provide a new name for:" %+% blurred(italic("(Leave blank to use same name)")))

		cat("\n")
		cat("-> " %+% bgWhite(black(currentcol)) )
		ask <- readline()
		newname <- ask
		if (ask == "") newname <- currentcol
		renamedDF$NewNames[i] <- newname
		renamedDF<-tibble::as_tibble(renamedDF)

	}
	colnames(FlatX$FlatResponses)<-renamedDF$NewNames
	print(renamedDF, n=min(100, nrow(renamedDF)))

	Output<-list()

	if (NamesDF==T) Output[[length(Output)+1]] <- renamedDF

	if (renameDF==T) Output[[length(Output)+1]] <- FlatX




}

